import type { CategoryInfo, ModelId, PaymentCardInfo, Product } from "@/types";

export const CATEGORIES: Record<string, CategoryInfo> = {
  dehumidifier: {
    id: "dehumidifier",
    name: "매직플러스 제습환기청정기",
    description: "습도 조절과 환기를 한번에",
    image: "/images/products/dehumidifier-THE6500.png",
    models: ["THE6500_150", "THE6500_200"],
  },
  "air-purifier": {
    id: "air-purifier",
    name: "매직플러스 환기청정기",
    description: "깨끗한 공기를 우리 집으로",
    image: "/images/products/air-purifier-TAA931.png",
    models: ["TAA931", "TAA530", "TAE530", "TAE330"],
  },
};

export const PRODUCTS: Record<ModelId, Product> = {
  THE6500_150: {
    id: "THE6500_150",
    category: "dehumidifier",
    name: "나비엔 매직플러스 제습환기 THE650 (150)",
    subtitle: "제습 + 환기 + 청정 올인원 · 36평형",
    description: "제습과 환기를 동시에 해결하는 프리미엄 제습환기청정기입니다. 150CMH 풍량으로 36평형까지 쾌적한 실내 습도를 유지하면서 신선한 외부 공기를 공급합니다.",
    image: "/images/products/dehumidifier-THE6500.png",
    rentalPrice: {
      selfManaged: 42900,
      visitManaged: 47900,
      period: 48,
    },
    purchasePrice: 1590000,
    specs: [
      { label: "모델명", value: "THE650-0150S" },
      { label: "타입", value: "매직플러스 제습환기청정기" },
      { label: "풍량", value: "150CMH" },
      { label: "적용면적", value: "36평형" },
      { label: "소비전력", value: "46W" },
      { label: "제습능력", value: "6.5L/일" },
      { label: "필터", value: "전열교환소자, 헤파필터, 탈취필터" },
      { label: "설치비", value: "무료" },
      { label: "렌탈기간", value: "48개월" },
    ],
  },
  THE6500_200: {
    id: "THE6500_200",
    category: "dehumidifier",
    name: "나비엔 매직플러스 제습환기 THE650 (200)",
    subtitle: "제습 + 환기 + 청정 올인원 · 48평형",
    description: "제습과 환기를 동시에 해결하는 프리미엄 제습환기청정기입니다. 200CMH 대용량 풍량으로 48평형까지 넓은 공간의 쾌적한 실내 환경을 제공합니다.",
    image: "/images/products/dehumidifier-THE6500.png",
    rentalPrice: {
      selfManaged: 47900,
      visitManaged: 52900,
      period: 48,
    },
    purchasePrice: 1790000,
    specs: [
      { label: "모델명", value: "THE650-0200S" },
      { label: "타입", value: "매직플러스 제습환기청정기" },
      { label: "풍량", value: "200CMH" },
      { label: "적용면적", value: "48평형" },
      { label: "소비전력", value: "56W" },
      { label: "제습능력", value: "8.0L/일" },
      { label: "필터", value: "전열교환소자, 헤파필터, 탈취필터" },
      { label: "설치비", value: "무료" },
      { label: "렌탈기간", value: "48개월" },
    ],
  },
  TAA931: {
    id: "TAA931",
    category: "air-purifier",
    name: "나비엔 매직플러스 환기청정 TAA931",
    subtitle: "대용량 환기청정",
    description: "넓은 공간에 적합한 대용량 환기청정기입니다. 강력한 공기 정화 성능으로 깨끗한 실내 환경을 만들어줍니다.",
    image: "/images/products/air-purifier-TAA931.png",
    rentalPrice: {
      selfManaged: 39900,
      visitManaged: 44900,
      period: 48,
    },
    purchasePrice: 1490000,
    specs: [
      { label: "모델명", value: "TAA931" },
      { label: "타입", value: "매직플러스 환기청정기" },
      { label: "풍량", value: "150CMH" },
      { label: "소비전력", value: "45W" },
      { label: "필터", value: "전열교환소자, 헤파필터, 탈취필터" },
      { label: "설치비", value: "무료" },
      { label: "렌탈기간", value: "48개월" },
    ],
  },
  TAA530: {
    id: "TAA530",
    category: "air-purifier",
    name: "나비엔 매직플러스 환기청정 TAA530",
    subtitle: "컴팩트 환기청정",
    description: "컴팩트한 사이즈로 다양한 공간에 설치 가능한 환기청정기입니다.",
    image: "/images/products/air-purifier-TAA530.png",
    rentalPrice: {
      selfManaged: 34900,
      visitManaged: 39900,
      period: 48,
    },
    purchasePrice: 1290000,
    specs: [
      { label: "모델명", value: "TAA530" },
      { label: "타입", value: "매직플러스 환기청정기" },
      { label: "풍량", value: "100CMH" },
      { label: "소비전력", value: "36W" },
      { label: "필터", value: "전열교환소자, 헤파필터, 탈취필터" },
      { label: "설치비", value: "무료" },
      { label: "렌탈기간", value: "48개월" },
    ],
  },
  TAE530: {
    id: "TAE530",
    category: "air-purifier",
    name: "나비엔 매직플러스 환기청정 TAE530",
    subtitle: "고성능 환기청정",
    description: "고성능 필터와 강력한 환기 시스템으로 최상의 공기질을 제공합니다.",
    image: "/images/products/air-purifier-TAE530.png",
    rentalPrice: {
      selfManaged: 29900,
      visitManaged: 34900,
      period: 48,
    },
    purchasePrice: 990000,
    specs: [
      { label: "모델명", value: "TAE530" },
      { label: "타입", value: "매직플러스 환기청정기" },
      { label: "풍량", value: "100CMH" },
      { label: "소비전력", value: "33W" },
      { label: "필터", value: "전열교환소자, 헤파필터" },
      { label: "설치비", value: "무료" },
      { label: "렌탈기간", value: "48개월" },
    ],
  },
  TAE330: {
    id: "TAE330",
    category: "air-purifier",
    name: "나비엔 매직플러스 환기청정 TAE330",
    subtitle: "에너지 절약형 환기청정",
    description: "에너지 효율이 높은 환기청정기로 경제적인 운영이 가능합니다.",
    image: "/images/products/air-purifier-TAE330.png",
    rentalPrice: {
      selfManaged: 25900,
      visitManaged: 30900,
      period: 48,
    },
    purchasePrice: 790000,
    specs: [
      { label: "모델명", value: "TAE330" },
      { label: "타입", value: "매직플러스 환기청정기" },
      { label: "풍량", value: "70CMH" },
      { label: "소비전력", value: "26W" },
      { label: "필터", value: "전열교환소자, 헤파필터" },
      { label: "설치비", value: "무료" },
      { label: "렌탈기간", value: "48개월" },
    ],
  },
};

export const PAYMENT_CARDS: Record<string, PaymentCardInfo> = {
  lotte: {
    id: "lotte",
    name: "롯데카드",
    color: "#ED1C24",
    textColor: "#FFFFFF",
    discount: "제휴 할인 혜택 제공",
    issuanceLink: "#",
  },
  hana: {
    id: "hana",
    name: "하나카드",
    color: "#009490",
    textColor: "#FFFFFF",
    discount: "제휴 할인 혜택 제공",
    issuanceLink: "#",
  },
};

export const CATEGORY_LIST = Object.values(CATEGORIES);
export const PRODUCT_LIST = Object.values(PRODUCTS);
